import { Preset } from '../types/types';

export const presets: Preset[] = [
  // ============ FAMOUS STABLE ORBITS ============
  {
    id: 'figure-8',
    name: 'Figure-8',
    description: 'Famous stable periodic orbit discovered by Moore (1993) and proven by Chenciner & Montgomery (2000)',
    category: 'famous',
    gravitationalConstant: 1,
    recommendedSpeed: 1,
    author: 'Cris Moore',
    year: 1993,
    bodies: [
      {
        name: 'Body A',
        position: { x: -0.97000436, y: 0.24308753, z: 0 },
        velocity: { x: 0.4662036850, y: 0.4323657300, z: 0 },
        mass: 1,
        color: '#ff6b6b',
        trailColor: '#ff6b6b',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: 0.97000436, y: -0.24308753, z: 0 },
        velocity: { x: 0.4662036850, y: 0.4323657300, z: 0 },
        mass: 1,
        color: '#4ecdc4',
        trailColor: '#4ecdc4',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: -0.93240737, y: -0.86473146, z: 0 },
        mass: 1,
        color: '#ffe66d',
        trailColor: '#ffe66d',
        radius: 0.08,
      },
    ],
  },
  {
    id: 'lagrange-equilateral',
    name: 'Lagrange Equilateral',
    description: 'Three equal masses rotating at vertices of equilateral triangle - discovered by Lagrange (1772)',
    category: 'famous',
    gravitationalConstant: 1,
    recommendedSpeed: 0.5,
    author: 'Joseph-Louis Lagrange',
    year: 1772,
    bodies: [
      {
        name: 'Body A',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0, y: 0.5, z: 0 },
        mass: 1,
        color: '#ff6b6b',
        trailColor: '#ff6b6b',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: -0.5, y: 0.866, z: 0 },
        velocity: { x: -0.433, y: -0.25, z: 0 },
        mass: 1,
        color: '#4ecdc4',
        trailColor: '#4ecdc4',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: -0.5, y: -0.866, z: 0 },
        velocity: { x: 0.433, y: -0.25, z: 0 },
        mass: 1,
        color: '#ffe66d',
        trailColor: '#ffe66d',
        radius: 0.08,
      },
    ],
  },
  {
    id: 'euler-collinear',
    name: 'Euler Collinear',
    description: 'Three bodies in a line rotating together - discovered by Euler (1767)',
    category: 'famous',
    gravitationalConstant: 1,
    recommendedSpeed: 0.8,
    author: 'Leonhard Euler',
    year: 1767,
    bodies: [
      {
        name: 'Body A',
        position: { x: -1.5, y: 0, z: 0 },
        velocity: { x: 0, y: -0.4, z: 0 },
        mass: 1,
        color: '#e74c3c',
        trailColor: '#e74c3c',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: 0, y: 0, z: 0 },
        mass: 2,
        color: '#f39c12',
        trailColor: '#f39c12',
        radius: 0.12,
      },
      {
        name: 'Body C',
        position: { x: 1.5, y: 0, z: 0 },
        velocity: { x: 0, y: 0.4, z: 0 },
        mass: 1,
        color: '#9b59b6',
        trailColor: '#9b59b6',
        radius: 0.08,
      },
    ],
  },

  // ============ PERIODIC CHOREOGRAPHIES ============
  {
    id: 'butterfly-i',
    name: 'Butterfly I',
    description: 'Butterfly-shaped periodic orbit',
    category: 'periodic',
    gravitationalConstant: 1,
    recommendedSpeed: 1,
    bodies: [
      {
        name: 'Body A',
        position: { x: -1, y: 0, z: 0 },
        velocity: { x: 0.30689, y: 0.12551, z: 0 },
        mass: 1,
        color: '#9b59b6',
        trailColor: '#9b59b6',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0.30689, y: 0.12551, z: 0 },
        mass: 1,
        color: '#3498db',
        trailColor: '#3498db',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: -0.61378, y: -0.25102, z: 0 },
        mass: 1,
        color: '#e74c3c',
        trailColor: '#e74c3c',
        radius: 0.08,
      },
    ],
  },
  {
    id: 'butterfly-ii',
    name: 'Butterfly II',
    description: 'Second butterfly variation',
    category: 'periodic',
    gravitationalConstant: 1,
    recommendedSpeed: 1,
    bodies: [
      {
        name: 'Body A',
        position: { x: -1, y: 0, z: 0 },
        velocity: { x: 0.39295, y: 0.09758, z: 0 },
        mass: 1,
        color: '#1abc9c',
        trailColor: '#1abc9c',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0.39295, y: 0.09758, z: 0 },
        mass: 1,
        color: '#e67e22',
        trailColor: '#e67e22',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: -0.78590, y: -0.19516, z: 0 },
        mass: 1,
        color: '#8e44ad',
        trailColor: '#8e44ad',
        radius: 0.08,
      },
    ],
  },
  {
    id: 'moth-i',
    name: 'Moth I',
    description: 'Moth-shaped periodic choreography',
    category: 'periodic',
    gravitationalConstant: 1,
    recommendedSpeed: 1,
    bodies: [
      {
        name: 'Body A',
        position: { x: -1, y: 0, z: 0 },
        velocity: { x: 0.46444, y: 0.39606, z: 0 },
        mass: 1,
        color: '#1abc9c',
        trailColor: '#1abc9c',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0.46444, y: 0.39606, z: 0 },
        mass: 1,
        color: '#f39c12',
        trailColor: '#f39c12',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: -0.92888, y: -0.79212, z: 0 },
        mass: 1,
        color: '#e91e63',
        trailColor: '#e91e63',
        radius: 0.08,
      },
    ],
  },
  {
    id: 'moth-ii',
    name: 'Moth II',
    description: 'Second moth variation',
    category: 'periodic',
    gravitationalConstant: 1,
    recommendedSpeed: 1,
    bodies: [
      {
        name: 'Body A',
        position: { x: -1, y: 0, z: 0 },
        velocity: { x: 0.43917, y: 0.45297, z: 0 },
        mass: 1,
        color: '#00bcd4',
        trailColor: '#00bcd4',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0.43917, y: 0.45297, z: 0 },
        mass: 1,
        color: '#ff5722',
        trailColor: '#ff5722',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: -0.87834, y: -0.90594, z: 0 },
        mass: 1,
        color: '#cddc39',
        trailColor: '#cddc39',
        radius: 0.08,
      },
    ],
  },
  {
    id: 'yarn',
    name: 'Yarn',
    description: 'Complex yarn-like periodic orbit',
    category: 'periodic',
    gravitationalConstant: 1,
    recommendedSpeed: 1,
    bodies: [
      {
        name: 'Body A',
        position: { x: -1, y: 0, z: 0 },
        velocity: { x: 0.55906, y: 0.34919, z: 0 },
        mass: 1,
        color: '#00bcd4',
        trailColor: '#00bcd4',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0.55906, y: 0.34919, z: 0 },
        mass: 1,
        color: '#ff5722',
        trailColor: '#ff5722',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: -1.11812, y: -0.69838, z: 0 },
        mass: 1,
        color: '#8bc34a',
        trailColor: '#8bc34a',
        radius: 0.08,
      },
    ],
  },
  {
    id: 'yin-yang-i',
    name: 'Yin Yang I',
    description: 'Yin-yang shaped periodic orbit',
    category: 'periodic',
    gravitationalConstant: 1,
    recommendedSpeed: 1,
    bodies: [
      {
        name: 'Body A',
        position: { x: -1, y: 0, z: 0 },
        velocity: { x: 0.51394, y: 0.30474, z: 0 },
        mass: 1,
        color: '#ffffff',
        trailColor: '#ffffff',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0.51394, y: 0.30474, z: 0 },
        mass: 1,
        color: '#2c3e50',
        trailColor: '#2c3e50',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: -1.02788, y: -0.60948, z: 0 },
        mass: 1,
        color: '#e74c3c',
        trailColor: '#e74c3c',
        radius: 0.08,
      },
    ],
  },
  {
    id: 'yin-yang-ii',
    name: 'Yin Yang II',
    description: 'Second yin-yang variation',
    category: 'periodic',
    gravitationalConstant: 1,
    recommendedSpeed: 1,
    bodies: [
      {
        name: 'Body A',
        position: { x: -1, y: 0, z: 0 },
        velocity: { x: 0.41682, y: 0.33033, z: 0 },
        mass: 1,
        color: '#ecf0f1',
        trailColor: '#ecf0f1',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0.41682, y: 0.33033, z: 0 },
        mass: 1,
        color: '#34495e',
        trailColor: '#34495e',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: -0.83364, y: -0.66066, z: 0 },
        mass: 1,
        color: '#3498db',
        trailColor: '#3498db',
        radius: 0.08,
      },
    ],
  },
  {
    id: 'dragonfly',
    name: 'Dragonfly',
    description: 'Dragonfly-shaped periodic orbit',
    category: 'periodic',
    gravitationalConstant: 1,
    recommendedSpeed: 1,
    bodies: [
      {
        name: 'Body A',
        position: { x: -1, y: 0, z: 0 },
        velocity: { x: 0.08330, y: 0.12789, z: 0 },
        mass: 1,
        color: '#00ff88',
        trailColor: '#00ff88',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0.08330, y: 0.12789, z: 0 },
        mass: 1,
        color: '#ff0088',
        trailColor: '#ff0088',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: -0.16660, y: -0.25578, z: 0 },
        mass: 1,
        color: '#0088ff',
        trailColor: '#0088ff',
        radius: 0.08,
      },
    ],
  },
  {
    id: 'goggles',
    name: 'Goggles',
    description: 'Goggles-shaped periodic orbit',
    category: 'periodic',
    gravitationalConstant: 1,
    recommendedSpeed: 1,
    bodies: [
      {
        name: 'Body A',
        position: { x: -1, y: 0, z: 0 },
        velocity: { x: 0.18428, y: 0.58719, z: 0 },
        mass: 1,
        color: '#ff4757',
        trailColor: '#ff4757',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0.18428, y: 0.58719, z: 0 },
        mass: 1,
        color: '#2ed573',
        trailColor: '#2ed573',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: -0.36856, y: -1.17438, z: 0 },
        mass: 1,
        color: '#ffa502',
        trailColor: '#ffa502',
        radius: 0.08,
      },
    ],
  },
  {
    id: 'bumblebee',
    name: 'Bumblebee',
    description: 'Bumblebee-shaped periodic orbit',
    category: 'periodic',
    gravitationalConstant: 1,
    recommendedSpeed: 1,
    bodies: [
      {
        name: 'Body A',
        position: { x: -1, y: 0, z: 0 },
        velocity: { x: 0.18939, y: 0.52672, z: 0 },
        mass: 1,
        color: '#f1c40f',
        trailColor: '#f1c40f',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0.18939, y: 0.52672, z: 0 },
        mass: 1,
        color: '#2c3e50',
        trailColor: '#2c3e50',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: -0.37878, y: -1.05344, z: 0 },
        mass: 1,
        color: '#f39c12',
        trailColor: '#f39c12',
        radius: 0.08,
      },
    ],
  },

  // ============ STABLE CONFIGURATIONS ============
  {
    id: 'stable-triangle',
    name: 'Stable Triangle',
    description: 'Stable triangular orbit with slight perturbation',
    category: 'stable',
    gravitationalConstant: 1,
    recommendedSpeed: 0.7,
    bodies: [
      {
        name: 'Body A',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0, y: 0.58, z: 0 },
        mass: 1,
        color: '#e74c3c',
        trailColor: '#e74c3c',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: -0.5, y: 0.866, z: 0 },
        velocity: { x: -0.502, y: -0.29, z: 0 },
        mass: 1,
        color: '#3498db',
        trailColor: '#3498db',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: -0.5, y: -0.866, z: 0 },
        velocity: { x: 0.502, y: -0.29, z: 0 },
        mass: 1,
        color: '#2ecc71',
        trailColor: '#2ecc71',
        radius: 0.08,
      },
    ],
  },

  // ============ CHAOTIC ============
  {
    id: 'chaotic-dance',
    name: 'Chaotic Dance',
    description: 'Three bodies in chaotic interaction',
    category: 'chaotic',
    gravitationalConstant: 1,
    recommendedSpeed: 0.8,
    bodies: [
      {
        name: 'Body A',
        position: { x: -1, y: 1, z: 0 },
        velocity: { x: 0.2, y: -0.1, z: 0 },
        mass: 1,
        color: '#ff6b6b',
        trailColor: '#ff6b6b',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: 1, y: 1, z: 0 },
        velocity: { x: -0.1, y: 0.2, z: 0 },
        mass: 1,
        color: '#4ecdc4',
        trailColor: '#4ecdc4',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: 0, y: -1, z: 0 },
        velocity: { x: -0.1, y: -0.1, z: 0 },
        mass: 1.5,
        color: '#ffe66d',
        trailColor: '#ffe66d',
        radius: 0.1,
      },
    ],
  },
  {
    id: 'slingshot',
    name: 'Slingshot',
    description: 'High-energy chaotic encounter',
    category: 'chaotic',
    gravitationalConstant: 1,
    recommendedSpeed: 0.5,
    bodies: [
      {
        name: 'Body A',
        position: { x: -2, y: 0, z: 0 },
        velocity: { x: 0.5, y: 0.3, z: 0 },
        mass: 2,
        color: '#e74c3c',
        trailColor: '#e74c3c',
        radius: 0.12,
      },
      {
        name: 'Body B',
        position: { x: 2, y: 0.5, z: 0 },
        velocity: { x: -0.5, y: 0, z: 0 },
        mass: 1,
        color: '#3498db',
        trailColor: '#3498db',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: 0, y: -1, z: 0 },
        velocity: { x: 0, y: 0.2, z: 0 },
        mass: 1,
        color: '#2ecc71',
        trailColor: '#2ecc71',
        radius: 0.08,
      },
    ],
  },
  {
    id: 'pythagorean',
    name: 'Pythagorean',
    description: 'Classic Pythagorean three-body problem (3-4-5 triangle)',
    category: 'chaotic',
    gravitationalConstant: 1,
    recommendedSpeed: 0.3,
    bodies: [
      {
        name: 'Body A',
        position: { x: 1, y: 3, z: 0 },
        velocity: { x: 0, y: 0, z: 0 },
        mass: 3,
        color: '#e74c3c',
        trailColor: '#e74c3c',
        radius: 0.12,
      },
      {
        name: 'Body B',
        position: { x: -2, y: -1, z: 0 },
        velocity: { x: 0, y: 0, z: 0 },
        mass: 4,
        color: '#3498db',
        trailColor: '#3498db',
        radius: 0.14,
      },
      {
        name: 'Body C',
        position: { x: 1, y: -1, z: 0 },
        velocity: { x: 0, y: 0, z: 0 },
        mass: 5,
        color: '#2ecc71',
        trailColor: '#2ecc71',
        radius: 0.16,
      },
    ],
  },
  {
    id: 'random-chaos',
    name: 'Random Chaos',
    description: 'Highly unpredictable chaotic motion',
    category: 'chaotic',
    gravitationalConstant: 1,
    recommendedSpeed: 0.6,
    bodies: [
      {
        name: 'Body A',
        position: { x: 0.5, y: 0.5, z: 0.2 },
        velocity: { x: 0.3, y: -0.2, z: 0.1 },
        mass: 1,
        color: '#e91e63',
        trailColor: '#e91e63',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: -0.8, y: 0.3, z: -0.1 },
        velocity: { x: -0.1, y: 0.4, z: -0.1 },
        mass: 1.2,
        color: '#00bcd4',
        trailColor: '#00bcd4',
        radius: 0.09,
      },
      {
        name: 'Body C',
        position: { x: 0.2, y: -0.9, z: -0.1 },
        velocity: { x: -0.2, y: -0.2, z: 0 },
        mass: 0.8,
        color: '#4caf50',
        trailColor: '#4caf50',
        radius: 0.07,
      },
    ],
  },

  // ============ FUN / INTERESTING ============
  {
    id: 'binary-plus-one',
    name: 'Binary + Intruder',
    description: 'Stable binary with a distant orbiter',
    category: 'fun',
    gravitationalConstant: 1,
    recommendedSpeed: 1,
    bodies: [
      {
        name: 'Star A',
        position: { x: -0.5, y: 0, z: 0 },
        velocity: { x: 0, y: -0.5, z: 0 },
        mass: 1,
        color: '#ff6b6b',
        trailColor: '#ff6b6b',
        radius: 0.08,
      },
      {
        name: 'Star B',
        position: { x: 0.5, y: 0, z: 0 },
        velocity: { x: 0, y: 0.5, z: 0 },
        mass: 1,
        color: '#4ecdc4',
        trailColor: '#4ecdc4',
        radius: 0.08,
      },
      {
        name: 'Planet',
        position: { x: 3, y: 0, z: 0 },
        velocity: { x: 0, y: 0.4, z: 0 },
        mass: 0.1,
        color: '#ffe66d',
        trailColor: '#ffe66d',
        radius: 0.04,
      },
    ],
  },
  {
    id: 'sun-earth-moon',
    name: 'Sun-Earth-Moon (Scaled)',
    description: 'Hierarchical system like our solar neighborhood',
    category: 'fun',
    gravitationalConstant: 1,
    recommendedSpeed: 2,
    bodies: [
      {
        name: 'Sun',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: 0, y: 0, z: 0 },
        mass: 10,
        color: '#f39c12',
        trailColor: '#f39c12',
        radius: 0.2,
      },
      {
        name: 'Earth',
        position: { x: 2, y: 0, z: 0 },
        velocity: { x: 0, y: 2.2, z: 0 },
        mass: 0.3,
        color: '#3498db',
        trailColor: '#3498db',
        radius: 0.08,
      },
      {
        name: 'Moon',
        position: { x: 2.2, y: 0, z: 0 },
        velocity: { x: 0, y: 2.8, z: 0 },
        mass: 0.01,
        color: '#95a5a6',
        trailColor: '#95a5a6',
        radius: 0.03,
      },
    ],
  },
  {
    id: 'alpha-centauri',
    name: 'Alpha Centauri (Simplified)',
    description: 'Simplified model of the Alpha Centauri system',
    category: 'fun',
    gravitationalConstant: 1,
    recommendedSpeed: 1.5,
    bodies: [
      {
        name: 'Alpha Centauri A',
        position: { x: -0.8, y: 0, z: 0 },
        velocity: { x: 0, y: -0.4, z: 0 },
        mass: 1.1,
        color: '#f1c40f',
        trailColor: '#f1c40f',
        radius: 0.1,
      },
      {
        name: 'Alpha Centauri B',
        position: { x: 0.8, y: 0, z: 0 },
        velocity: { x: 0, y: 0.44, z: 0 },
        mass: 0.9,
        color: '#e67e22',
        trailColor: '#e67e22',
        radius: 0.09,
      },
      {
        name: 'Proxima Centauri',
        position: { x: 4, y: 0, z: 0.5 },
        velocity: { x: 0, y: 0.25, z: 0 },
        mass: 0.12,
        color: '#e74c3c',
        trailColor: '#e74c3c',
        radius: 0.04,
      },
    ],
  },
  {
    id: 'hot-jupiter',
    name: 'Hot Jupiter System',
    description: 'Star with close-orbiting giant planet and distant companion',
    category: 'fun',
    gravitationalConstant: 1,
    recommendedSpeed: 3,
    bodies: [
      {
        name: 'Star',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: 0, y: -0.05, z: 0 },
        mass: 5,
        color: '#f39c12',
        trailColor: '#f39c12',
        radius: 0.15,
      },
      {
        name: 'Hot Jupiter',
        position: { x: 0.5, y: 0, z: 0 },
        velocity: { x: 0, y: 3.2, z: 0 },
        mass: 0.5,
        color: '#e74c3c',
        trailColor: '#e74c3c',
        radius: 0.1,
      },
      {
        name: 'Distant Planet',
        position: { x: 3, y: 0, z: 0 },
        velocity: { x: 0, y: 1.3, z: 0 },
        mass: 0.1,
        color: '#3498db',
        trailColor: '#3498db',
        radius: 0.06,
      },
    ],
  },

  // ============ 3D ORBITS ============
  {
    id: '3d-helix',
    name: '3D Helix',
    description: 'Three bodies in a 3D helical dance',
    category: 'fun',
    gravitationalConstant: 1,
    recommendedSpeed: 0.8,
    bodies: [
      {
        name: 'Body A',
        position: { x: 1, y: 0, z: 0.5 },
        velocity: { x: 0, y: 0.5, z: 0.1 },
        mass: 1,
        color: '#ff6b6b',
        trailColor: '#ff6b6b',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: -0.5, y: 0.866, z: -0.25 },
        velocity: { x: -0.433, y: -0.25, z: 0.1 },
        mass: 1,
        color: '#4ecdc4',
        trailColor: '#4ecdc4',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: -0.5, y: -0.866, z: -0.25 },
        velocity: { x: 0.433, y: -0.25, z: -0.2 },
        mass: 1,
        color: '#ffe66d',
        trailColor: '#ffe66d',
        radius: 0.08,
      },
    ],
  },
  {
    id: '3d-sphere',
    name: '3D Sphere Dance',
    description: 'Bodies orbiting in 3D spherical pattern',
    category: 'fun',
    gravitationalConstant: 1,
    recommendedSpeed: 0.6,
    bodies: [
      {
        name: 'Body A',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0, y: 0.3, z: 0.4 },
        mass: 1,
        color: '#9b59b6',
        trailColor: '#9b59b6',
        radius: 0.08,
      },
      {
        name: 'Body B',
        position: { x: 0, y: 1, z: 0 },
        velocity: { x: 0.4, y: 0, z: 0.3 },
        mass: 1,
        color: '#1abc9c',
        trailColor: '#1abc9c',
        radius: 0.08,
      },
      {
        name: 'Body C',
        position: { x: 0, y: 0, z: 1 },
        velocity: { x: 0.3, y: 0.4, z: 0 },
        mass: 1,
        color: '#e74c3c',
        trailColor: '#e74c3c',
        radius: 0.08,
      },
    ],
  },

  // ============ ARTISTIC ============
  {
    id: 'flower',
    name: 'Flower Pattern',
    description: 'Creates beautiful flower-like trails',
    category: 'artistic',
    gravitationalConstant: 1,
    recommendedSpeed: 1.2,
    bodies: [
      {
        name: 'Petal A',
        position: { x: -1, y: 0, z: 0 },
        velocity: { x: 0.34, y: 0.53, z: 0 },
        mass: 1,
        color: '#ff69b4',
        trailColor: '#ff69b4',
        radius: 0.06,
      },
      {
        name: 'Petal B',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0.34, y: 0.53, z: 0 },
        mass: 1,
        color: '#ff1493',
        trailColor: '#ff1493',
        radius: 0.06,
      },
      {
        name: 'Center',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: -0.68, y: -1.06, z: 0 },
        mass: 1,
        color: '#ffd700',
        trailColor: '#ffd700',
        radius: 0.06,
      },
    ],
  },
  {
    id: 'galaxy-spiral',
    name: 'Galaxy Spiral',
    description: 'Creates spiral galaxy-like patterns',
    category: 'artistic',
    gravitationalConstant: 0.8,
    recommendedSpeed: 0.8,
    bodies: [
      {
        name: 'Core',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: 0, y: 0, z: 0 },
        mass: 3,
        color: '#ffeaa7',
        trailColor: '#ffeaa7',
        radius: 0.15,
      },
      {
        name: 'Arm A',
        position: { x: 1.5, y: 0.5, z: 0 },
        velocity: { x: -0.2, y: 0.8, z: 0.1 },
        mass: 0.5,
        color: '#74b9ff',
        trailColor: '#74b9ff',
        radius: 0.06,
      },
      {
        name: 'Arm B',
        position: { x: -1, y: -1.2, z: 0.2 },
        velocity: { x: 0.6, y: -0.3, z: -0.1 },
        mass: 0.5,
        color: '#a29bfe',
        trailColor: '#a29bfe',
        radius: 0.06,
      },
    ],
  },
  {
    id: 'infinity',
    name: 'Infinity Symbol',
    description: 'Traces an infinity-like pattern',
    category: 'artistic',
    gravitationalConstant: 1,
    recommendedSpeed: 1,
    bodies: [
      {
        name: 'Body A',
        position: { x: -1, y: 0, z: 0 },
        velocity: { x: 0.347, y: 0.533, z: 0 },
        mass: 1,
        color: '#00cec9',
        trailColor: '#00cec9',
        radius: 0.07,
      },
      {
        name: 'Body B',
        position: { x: 1, y: 0, z: 0 },
        velocity: { x: 0.347, y: 0.533, z: 0 },
        mass: 1,
        color: '#fd79a8',
        trailColor: '#fd79a8',
        radius: 0.07,
      },
      {
        name: 'Body C',
        position: { x: 0, y: 0, z: 0 },
        velocity: { x: -0.694, y: -1.066, z: 0 },
        mass: 1,
        color: '#fdcb6e',
        trailColor: '#fdcb6e',
        radius: 0.07,
      },
    ],
  },
  {
    id: 'neon-dance',
    name: 'Neon Dance',
    description: 'Vibrant neon-colored chaotic dance',
    category: 'artistic',
    gravitationalConstant: 1,
    recommendedSpeed: 0.7,
    bodies: [
      {
        name: 'Neon Pink',
        position: { x: 0.8, y: 0.6, z: 0 },
        velocity: { x: -0.3, y: 0.4, z: 0 },
        mass: 1,
        color: '#ff00ff',
        trailColor: '#ff00ff',
        radius: 0.08,
      },
      {
        name: 'Neon Cyan',
        position: { x: -0.8, y: 0.6, z: 0 },
        velocity: { x: 0.3, y: 0.4, z: 0 },
        mass: 1,
        color: '#00ffff',
        trailColor: '#00ffff',
        radius: 0.08,
      },
      {
        name: 'Neon Yellow',
        position: { x: 0, y: -1, z: 0 },
        velocity: { x: 0, y: -0.3, z: 0 },
        mass: 1.2,
        color: '#ffff00',
        trailColor: '#ffff00',
        radius: 0.09,
      },
    ],
  },
];

export const getPresetsByCategory = (category: Preset['category']) => {
  return presets.filter((p) => p.category === category);
};

export const getPresetById = (id: string) => {
  return presets.find((p) => p.id === id);
};

export const getAllCategories = (): Preset['category'][] => {
  return ['famous', 'stable', 'periodic', 'chaotic', 'fun', 'artistic'];
};
