// src/games/threebodyproblem/presets/presets.ts

import {Preset} from '../types/types';

export const presets: Preset[] = [
    // =====================================================
    // FAMOUS HISTORICAL DISCOVERIES
    // =====================================================
    {
        id: 'figure-8',
        name: 'Figure-8',
        description: 'Famous stable periodic orbit discovered by Moore (1993)',
        category: 'famous',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        author: 'Cris Moore',
        year: 1993,
        bodies: [
            {
                name: 'Body A',
                position: {x: -0.97000436, y: 0.24308753, z: 0},
                velocity: {x: 0.4662036850, y: 0.4323657300, z: 0},
                mass: 1,
                color: '#ff6b6b',
                trailColor: '#ff6b6b',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 0.97000436, y: -0.24308753, z: 0},
                velocity: {x: 0.4662036850, y: 0.4323657300, z: 0},
                mass: 1,
                color: '#4ecdc4',
                trailColor: '#4ecdc4',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.93240737, y: -0.86473146, z: 0},
                mass: 1,
                color: '#ffe66d',
                trailColor: '#ffe66d',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'lagrange-equilateral',
        name: 'Lagrange Equilateral',
        description: 'Three equal masses at equilateral triangle vertices',
        category: 'famous',
        gravitationalConstant: 1,
        recommendedSpeed: 0.5,
        author: 'Joseph-Louis Lagrange',
        year: 1772,
        bodies: [
            {
                name: 'Body A',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0, y: 0.5, z: 0},
                mass: 1,
                color: '#ff6b6b',
                trailColor: '#ff6b6b',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: -0.5, y: 0.866025, z: 0},
                velocity: {x: -0.433013, y: -0.25, z: 0},
                mass: 1,
                color: '#4ecdc4',
                trailColor: '#4ecdc4',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: -0.5, y: -0.866025, z: 0},
                velocity: {x: 0.433013, y: -0.25, z: 0},
                mass: 1,
                color: '#ffe66d',
                trailColor: '#ffe66d',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'euler-collinear',
        name: 'Euler Collinear',
        description: 'Three bodies rotating in a line',
        category: 'famous',
        gravitationalConstant: 1,
        recommendedSpeed: 0.6,
        author: 'Leonhard Euler',
        year: 1767,
        bodies: [
            {
                name: 'Left',
                position: {x: -1.5, y: 0, z: 0},
                velocity: {x: 0, y: -0.35, z: 0},
                mass: 1,
                color: '#e74c3c',
                trailColor: '#e74c3c',
                radius: 0.08,
            },
            {
                name: 'Center',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: 0, y: 0, z: 0},
                mass: 2,
                color: '#f39c12',
                trailColor: '#f39c12',
                radius: 0.12,
            },
            {
                name: 'Right',
                position: {x: 1.5, y: 0, z: 0},
                velocity: {x: 0, y: 0.35, z: 0},
                mass: 1,
                color: '#9b59b6',
                trailColor: '#9b59b6',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'broucke-a1',
        name: 'Broucke A1',
        description: 'Broucke-Hadjidemetriou-Hénon orbit family A1',
        category: 'famous',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        author: 'Roger Broucke',
        year: 1975,
        bodies: [
            {
                name: 'Body A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.2059, y: 0.4090, z: 0},
                mass: 1,
                color: '#e91e63',
                trailColor: '#e91e63',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.2059, y: 0.4090, z: 0},
                mass: 1,
                color: '#00bcd4',
                trailColor: '#00bcd4',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.4118, y: -0.8180, z: 0},
                mass: 1,
                color: '#8bc34a',
                trailColor: '#8bc34a',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'broucke-a2',
        name: 'Broucke A2',
        description: 'Broucke-Hadjidemetriou-Hénon orbit family A2',
        category: 'famous',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        author: 'Roger Broucke',
        year: 1975,
        bodies: [
            {
                name: 'Body A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.3471, y: 0.5327, z: 0},
                mass: 1,
                color: '#ff5722',
                trailColor: '#ff5722',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.3471, y: 0.5327, z: 0},
                mass: 1,
                color: '#3f51b5',
                trailColor: '#3f51b5',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.6942, y: -1.0654, z: 0},
                mass: 1,
                color: '#4caf50',
                trailColor: '#4caf50',
                radius: 0.08,
            },
        ],
    },

    // =====================================================
    // PERIODIC CHOREOGRAPHIES
    // =====================================================
    {
        id: 'butterfly-i',
        name: 'Butterfly I',
        description: 'Butterfly-shaped periodic orbit',
        category: 'periodic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Body A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.30689, y: 0.12551, z: 0},
                mass: 1,
                color: '#9b59b6',
                trailColor: '#9b59b6',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.30689, y: 0.12551, z: 0},
                mass: 1,
                color: '#3498db',
                trailColor: '#3498db',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.61378, y: -0.25102, z: 0},
                mass: 1,
                color: '#e74c3c',
                trailColor: '#e74c3c',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'butterfly-ii',
        name: 'Butterfly II',
        description: 'Second butterfly variation',
        category: 'periodic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Body A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.39295, y: 0.09758, z: 0},
                mass: 1,
                color: '#1abc9c',
                trailColor: '#1abc9c',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.39295, y: 0.09758, z: 0},
                mass: 1,
                color: '#e67e22',
                trailColor: '#e67e22',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.78590, y: -0.19516, z: 0},
                mass: 1,
                color: '#8e44ad',
                trailColor: '#8e44ad',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'butterfly-iii',
        name: 'Butterfly III',
        description: 'Third butterfly variation',
        category: 'periodic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Body A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.40592, y: 0.23016, z: 0},
                mass: 1,
                color: '#00bcd4',
                trailColor: '#00bcd4',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.40592, y: 0.23016, z: 0},
                mass: 1,
                color: '#ff9800',
                trailColor: '#ff9800',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.81184, y: -0.46032, z: 0},
                mass: 1,
                color: '#673ab7',
                trailColor: '#673ab7',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'moth-i',
        name: 'Moth I',
        description: 'Moth-shaped periodic choreography',
        category: 'periodic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Body A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.46444, y: 0.39606, z: 0},
                mass: 1,
                color: '#1abc9c',
                trailColor: '#1abc9c',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.46444, y: 0.39606, z: 0},
                mass: 1,
                color: '#f39c12',
                trailColor: '#f39c12',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.92888, y: -0.79212, z: 0},
                mass: 1,
                color: '#e91e63',
                trailColor: '#e91e63',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'moth-ii',
        name: 'Moth II',
        description: 'Second moth variation',
        category: 'periodic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Body A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.43917, y: 0.45297, z: 0},
                mass: 1,
                color: '#00bcd4',
                trailColor: '#00bcd4',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.43917, y: 0.45297, z: 0},
                mass: 1,
                color: '#ff5722',
                trailColor: '#ff5722',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.87834, y: -0.90594, z: 0},
                mass: 1,
                color: '#cddc39',
                trailColor: '#cddc39',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'moth-iii',
        name: 'Moth III',
        description: 'Third moth variation',
        category: 'periodic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Body A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.38344, y: 0.37736, z: 0},
                mass: 1,
                color: '#9c27b0',
                trailColor: '#9c27b0',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.38344, y: 0.37736, z: 0},
                mass: 1,
                color: '#03a9f4',
                trailColor: '#03a9f4',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.76688, y: -0.75472, z: 0},
                mass: 1,
                color: '#ffeb3b',
                trailColor: '#ffeb3b',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'yarn',
        name: 'Yarn',
        description: 'Complex yarn-like periodic orbit',
        category: 'periodic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Body A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.55906, y: 0.34919, z: 0},
                mass: 1,
                color: '#00bcd4',
                trailColor: '#00bcd4',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.55906, y: 0.34919, z: 0},
                mass: 1,
                color: '#ff5722',
                trailColor: '#ff5722',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -1.11812, y: -0.69838, z: 0},
                mass: 1,
                color: '#8bc34a',
                trailColor: '#8bc34a',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'yin-yang-i',
        name: 'Yin Yang I',
        description: 'Yin-yang shaped periodic orbit',
        category: 'periodic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Yin',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.51394, y: 0.30474, z: 0},
                mass: 1,
                color: '#ffffff',
                trailColor: '#ffffff',
                radius: 0.08,
            },
            {
                name: 'Yang',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.51394, y: 0.30474, z: 0},
                mass: 1,
                color: '#2c3e50',
                trailColor: '#2c3e50',
                radius: 0.08,
            },
            {
                name: 'Balance',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -1.02788, y: -0.60948, z: 0},
                mass: 1,
                color: '#e74c3c',
                trailColor: '#e74c3c',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'yin-yang-ii',
        name: 'Yin Yang II',
        description: 'Second yin-yang variation',
        category: 'periodic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Yin',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.41682, y: 0.33033, z: 0},
                mass: 1,
                color: '#ecf0f1',
                trailColor: '#ecf0f1',
                radius: 0.08,
            },
            {
                name: 'Yang',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.41682, y: 0.33033, z: 0},
                mass: 1,
                color: '#34495e',
                trailColor: '#34495e',
                radius: 0.08,
            },
            {
                name: 'Balance',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.83364, y: -0.66066, z: 0},
                mass: 1,
                color: '#3498db',
                trailColor: '#3498db',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'dragonfly',
        name: 'Dragonfly',
        description: 'Dragonfly-shaped periodic orbit',
        category: 'periodic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Wing A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.08330, y: 0.12789, z: 0},
                mass: 1,
                color: '#00ff88',
                trailColor: '#00ff88',
                radius: 0.08,
            },
            {
                name: 'Wing B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.08330, y: 0.12789, z: 0},
                mass: 1,
                color: '#ff0088',
                trailColor: '#ff0088',
                radius: 0.08,
            },
            {
                name: 'Body',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.16660, y: -0.25578, z: 0},
                mass: 1,
                color: '#0088ff',
                trailColor: '#0088ff',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'goggles',
        name: 'Goggles',
        description: 'Goggles-shaped periodic orbit',
        category: 'periodic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Left Lens',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.18428, y: 0.58719, z: 0},
                mass: 1,
                color: '#ff4757',
                trailColor: '#ff4757',
                radius: 0.08,
            },
            {
                name: 'Right Lens',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.18428, y: 0.58719, z: 0},
                mass: 1,
                color: '#2ed573',
                trailColor: '#2ed573',
                radius: 0.08,
            },
            {
                name: 'Bridge',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.36856, y: -1.17438, z: 0},
                mass: 1,
                color: '#ffa502',
                trailColor: '#ffa502',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'bumblebee',
        name: 'Bumblebee',
        description: 'Bumblebee-shaped periodic orbit',
        category: 'periodic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Wing A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.18939, y: 0.52672, z: 0},
                mass: 1,
                color: '#f1c40f',
                trailColor: '#f1c40f',
                radius: 0.08,
            },
            {
                name: 'Wing B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.18939, y: 0.52672, z: 0},
                mass: 1,
                color: '#2c3e50',
                trailColor: '#2c3e50',
                radius: 0.08,
            },
            {
                name: 'Body',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.37878, y: -1.05344, z: 0},
                mass: 1,
                color: '#f39c12',
                trailColor: '#f39c12',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'ovals',
        name: 'Ovals',
        description: 'Interweaving oval patterns',
        category: 'periodic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Body A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.14279, y: 0.50989, z: 0},
                mass: 1,
                color: '#e91e63',
                trailColor: '#e91e63',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.14279, y: 0.50989, z: 0},
                mass: 1,
                color: '#2196f3',
                trailColor: '#2196f3',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.28558, y: -1.01978, z: 0},
                mass: 1,
                color: '#4caf50',
                trailColor: '#4caf50',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'trefoil',
        name: 'Trefoil',
        description: 'Three-lobed periodic orbit',
        category: 'periodic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Body A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.32995, y: 0.45962, z: 0},
                mass: 1,
                color: '#9c27b0',
                trailColor: '#9c27b0',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.32995, y: 0.45962, z: 0},
                mass: 1,
                color: '#00bcd4',
                trailColor: '#00bcd4',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.65990, y: -0.91924, z: 0},
                mass: 1,
                color: '#ffeb3b',
                trailColor: '#ffeb3b',
                radius: 0.08,
            },
        ],
    },

    // =====================================================
    // STABLE CONFIGURATIONS
    // =====================================================
    {
        id: 'stable-triangle',
        name: 'Stable Triangle',
        description: 'Stable triangular configuration',
        category: 'stable',
        gravitationalConstant: 1,
        recommendedSpeed: 0.7,
        bodies: [
            {
                name: 'Vertex A',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0, y: 0.58, z: 0},
                mass: 1,
                color: '#e74c3c',
                trailColor: '#e74c3c',
                radius: 0.08,
            },
            {
                name: 'Vertex B',
                position: {x: -0.5, y: 0.866025, z: 0},
                velocity: {x: -0.502, y: -0.29, z: 0},
                mass: 1,
                color: '#3498db',
                trailColor: '#3498db',
                radius: 0.08,
            },
            {
                name: 'Vertex C',
                position: {x: -0.5, y: -0.866025, z: 0},
                velocity: {x: 0.502, y: -0.29, z: 0},
                mass: 1,
                color: '#2ecc71',
                trailColor: '#2ecc71',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'wide-binary',
        name: 'Wide Binary + Planet',
        description: 'Wide binary star with distant planet',
        category: 'stable',
        gravitationalConstant: 1,
        recommendedSpeed: 0.8,
        bodies: [
            {
                name: 'Star A',
                position: {x: -1.5, y: 0, z: 0},
                velocity: {x: 0, y: -0.3, z: 0},
                mass: 1.5,
                color: '#f39c12',
                trailColor: '#f39c12',
                radius: 0.1,
            },
            {
                name: 'Star B',
                position: {x: 1.5, y: 0, z: 0},
                velocity: {x: 0, y: 0.3, z: 0},
                mass: 1.5,
                color: '#e74c3c',
                trailColor: '#e74c3c',
                radius: 0.1,
            },
            {
                name: 'Planet',
                position: {x: 0, y: 4, z: 0},
                velocity: {x: 0.5, y: 0, z: 0},
                mass: 0.1,
                color: '#3498db',
                trailColor: '#3498db',
                radius: 0.04,
            },
        ],
    },
    {
        id: 'hierarchical',
        name: 'Hierarchical Triple',
        description: 'Tight binary with distant third body',
        category: 'stable',
        gravitationalConstant: 1,
        recommendedSpeed: 1.5,
        bodies: [
            {
                name: 'Primary',
                position: {x: -0.3, y: 0, z: 0},
                velocity: {x: 0, y: -0.8, z: 0},
                mass: 1,
                color: '#f1c40f',
                trailColor: '#f1c40f',
                radius: 0.08,
            },
            {
                name: 'Secondary',
                position: {x: 0.3, y: 0, z: 0},
                velocity: {x: 0, y: 0.8, z: 0},
                mass: 1,
                color: '#e67e22',
                trailColor: '#e67e22',
                radius: 0.08,
            },
            {
                name: 'Tertiary',
                position: {x: 4, y: 0, z: 0},
                velocity: {x: 0, y: 0.5, z: 0},
                mass: 0.5,
                color: '#9b59b6',
                trailColor: '#9b59b6',
                radius: 0.06,
            },
        ],
    },

    // =====================================================
    // CHAOTIC CONFIGURATIONS
    // =====================================================
    {
        id: 'chaotic-dance',
        name: 'Chaotic Dance',
        description: 'Three bodies in chaotic interaction',
        category: 'chaotic',
        gravitationalConstant: 1,
        recommendedSpeed: 0.8,
        bodies: [
            {
                name: 'Body A',
                position: {x: -1, y: 1, z: 0},
                velocity: {x: 0.2, y: -0.1, z: 0},
                mass: 1,
                color: '#ff6b6b',
                trailColor: '#ff6b6b',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 1, y: 1, z: 0},
                velocity: {x: -0.1, y: 0.2, z: 0},
                mass: 1,
                color: '#4ecdc4',
                trailColor: '#4ecdc4',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: -1, z: 0},
                velocity: {x: -0.1, y: -0.1, z: 0},
                mass: 1.5,
                color: '#ffe66d',
                trailColor: '#ffe66d',
                radius: 0.1,
            },
        ],
    },
    {
        id: 'slingshot',
        name: 'Slingshot',
        description: 'High-energy chaotic encounter',
        category: 'chaotic',
        gravitationalConstant: 1,
        recommendedSpeed: 0.5,
        bodies: [
            {
                name: 'Heavy',
                position: {x: -2, y: 0, z: 0},
                velocity: {x: 0.5, y: 0.3, z: 0},
                mass: 2,
                color: '#e74c3c',
                trailColor: '#e74c3c',
                radius: 0.12,
            },
            {
                name: 'Medium',
                position: {x: 2, y: 0.5, z: 0},
                velocity: {x: -0.5, y: 0, z: 0},
                mass: 1,
                color: '#3498db',
                trailColor: '#3498db',
                radius: 0.08,
            },
            {
                name: 'Light',
                position: {x: 0, y: -1, z: 0},
                velocity: {x: 0, y: 0.2, z: 0},
                mass: 0.5,
                color: '#2ecc71',
                trailColor: '#2ecc71',
                radius: 0.06,
            },
        ],
    },
    {
        id: 'pythagorean',
        name: 'Pythagorean',
        description: 'Classic 3-4-5 triangle problem',
        category: 'chaotic',
        gravitationalConstant: 1,
        recommendedSpeed: 0.3,
        bodies: [
            {
                name: 'Mass 3',
                position: {x: 1, y: 3, z: 0},
                velocity: {x: 0, y: 0, z: 0},
                mass: 3,
                color: '#e74c3c',
                trailColor: '#e74c3c',
                radius: 0.12,
            },
            {
                name: 'Mass 4',
                position: {x: -2, y: -1, z: 0},
                velocity: {x: 0, y: 0, z: 0},
                mass: 4,
                color: '#3498db',
                trailColor: '#3498db',
                radius: 0.14,
            },
            {
                name: 'Mass 5',
                position: {x: 1, y: -1, z: 0},
                velocity: {x: 0, y: 0, z: 0},
                mass: 5,
                color: '#2ecc71',
                trailColor: '#2ecc71',
                radius: 0.16,
            },
        ],
    },
    {
        id: 'free-fall',
        name: 'Free Fall Collision',
        description: 'Three bodies falling towards each other',
        category: 'chaotic',
        gravitationalConstant: 1,
        recommendedSpeed: 0.4,
        bodies: [
            {
                name: 'Body A',
                position: {x: 2, y: 0, z: 0},
                velocity: {x: 0, y: 0.1, z: 0},
                mass: 1,
                color: '#ff6b6b',
                trailColor: '#ff6b6b',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: -1, y: 1.732, z: 0},
                velocity: {x: 0.087, y: -0.05, z: 0},
                mass: 1,
                color: '#4ecdc4',
                trailColor: '#4ecdc4',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: -1, y: -1.732, z: 0},
                velocity: {x: -0.087, y: -0.05, z: 0},
                mass: 1,
                color: '#ffe66d',
                trailColor: '#ffe66d',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'near-collision',
        name: 'Near Collision',
        description: 'Close encounters and near misses',
        category: 'chaotic',
        gravitationalConstant: 1,
        recommendedSpeed: 0.6,
        bodies: [
            {
                name: 'Body A',
                position: {x: -2, y: 0.1, z: 0},
                velocity: {x: 0.6, y: 0, z: 0},
                mass: 1,
                color: '#e91e63',
                trailColor: '#e91e63',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 2, y: -0.1, z: 0},
                velocity: {x: -0.6, y: 0, z: 0},
                mass: 1,
                color: '#00bcd4',
                trailColor: '#00bcd4',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 2, z: 0},
                velocity: {x: 0, y: -0.4, z: 0},
                mass: 1,
                color: '#8bc34a',
                trailColor: '#8bc34a',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'wild-spin',
        name: 'Wild Spin',
        description: 'Unpredictable spinning chaos',
        category: 'chaotic',
        gravitationalConstant: 1,
        recommendedSpeed: 0.7,
        bodies: [
            {
                name: 'Body A',
                position: {x: 0.5, y: 0.5, z: 0},
                velocity: {x: 0.5, y: -0.5, z: 0},
                mass: 1,
                color: '#ff5722',
                trailColor: '#ff5722',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: -0.5, y: 0.5, z: 0},
                velocity: {x: -0.3, y: -0.3, z: 0},
                mass: 1.2,
                color: '#673ab7',
                trailColor: '#673ab7',
                radius: 0.09,
            },
            {
                name: 'Body C',
                position: {x: 0, y: -1, z: 0},
                velocity: {x: -0.2, y: 0.8, z: 0},
                mass: 0.8,
                color: '#009688',
                trailColor: '#009688',
                radius: 0.07,
            },
        ],
    },

    // =====================================================
    // FUN / INTERESTING
    // =====================================================
    {
        id: 'binary-plus-one',
        name: 'Binary + Orbiter',
        description: 'Stable binary with distant orbiter',
        category: 'fun',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Star A',
                position: {x: -0.5, y: 0, z: 0},
                velocity: {x: 0, y: -0.5, z: 0},
                mass: 1,
                color: '#ff6b6b',
                trailColor: '#ff6b6b',
                radius: 0.08,
            },
            {
                name: 'Star B',
                position: {x: 0.5, y: 0, z: 0},
                velocity: {x: 0, y: 0.5, z: 0},
                mass: 1,
                color: '#4ecdc4',
                trailColor: '#4ecdc4',
                radius: 0.08,
            },
            {
                name: 'Planet',
                position: {x: 3, y: 0, z: 0},
                velocity: {x: 0, y: 0.45, z: 0},
                mass: 0.1,
                color: '#ffe66d',
                trailColor: '#ffe66d',
                radius: 0.04,
            },
        ],
    },
    {
        id: 'sun-earth-moon',
        name: 'Sun-Earth-Moon',
        description: 'Simplified solar system model',
        category: 'fun',
        gravitationalConstant: 1,
        recommendedSpeed: 2,
        bodies: [
            {
                name: 'Sun',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: 0, y: 0, z: 0},
                mass: 10,
                color: '#f39c12',
                trailColor: '#f39c12',
                radius: 0.2,
            },
            {
                name: 'Earth',
                position: {x: 2, y: 0, z: 0},
                velocity: {x: 0, y: 2.2, z: 0},
                mass: 0.3,
                color: '#3498db',
                trailColor: '#3498db',
                radius: 0.08,
            },
            {
                name: 'Moon',
                position: {x: 2.2, y: 0, z: 0},
                velocity: {x: 0, y: 2.8, z: 0},
                mass: 0.01,
                color: '#95a5a6',
                trailColor: '#95a5a6',
                radius: 0.03,
            },
        ],
    },
    {
        id: 'alpha-centauri',
        name: 'Alpha Centauri',
        description: 'Simplified Alpha Centauri system',
        category: 'fun',
        gravitationalConstant: 1,
        recommendedSpeed: 1.5,
        bodies: [
            {
                name: 'Alpha Centauri A',
                position: {x: -0.8, y: 0, z: 0},
                velocity: {x: 0, y: -0.4, z: 0},
                mass: 1.1,
                color: '#f1c40f',
                trailColor: '#f1c40f',
                radius: 0.1,
            },
            {
                name: 'Alpha Centauri B',
                position: {x: 0.8, y: 0, z: 0},
                velocity: {x: 0, y: 0.44, z: 0},
                mass: 0.9,
                color: '#e67e22',
                trailColor: '#e67e22',
                radius: 0.09,
            },
            {
                name: 'Proxima Centauri',
                position: {x: 4, y: 0, z: 0.5},
                velocity: {x: 0, y: 0.25, z: 0},
                mass: 0.12,
                color: '#e74c3c',
                trailColor: '#e74c3c',
                radius: 0.04,
            },
        ],
    },
    {
        id: 'hot-jupiter',
        name: 'Hot Jupiter System',
        description: 'Star with close giant planet',
        category: 'fun',
        gravitationalConstant: 1,
        recommendedSpeed: 3,
        bodies: [
            {
                name: 'Star',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: 0, y: -0.05, z: 0},
                mass: 5,
                color: '#f39c12',
                trailColor: '#f39c12',
                radius: 0.15,
            },
            {
                name: 'Hot Jupiter',
                position: {x: 0.5, y: 0, z: 0},
                velocity: {x: 0, y: 3.2, z: 0},
                mass: 0.5,
                color: '#e74c3c',
                trailColor: '#e74c3c',
                radius: 0.1,
            },
            {
                name: 'Outer Planet',
                position: {x: 3, y: 0, z: 0},
                velocity: {x: 0, y: 1.3, z: 0},
                mass: 0.1,
                color: '#3498db',
                trailColor: '#3498db',
                radius: 0.06,
            },
        ],
    },
    {
        id: 'trappist',
        name: 'TRAPPIST-like',
        description: 'Compact multi-planet system',
        category: 'fun',
        gravitationalConstant: 1,
        recommendedSpeed: 2.5,
        bodies: [
            {
                name: 'Red Dwarf',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: 0, y: 0, z: 0},
                mass: 3,
                color: '#c0392b',
                trailColor: '#c0392b',
                radius: 0.12,
            },
            {
                name: 'Planet b',
                position: {x: 0.8, y: 0, z: 0},
                velocity: {x: 0, y: 1.9, z: 0},
                mass: 0.1,
                color: '#2980b9',
                trailColor: '#2980b9',
                radius: 0.05,
            },
            {
                name: 'Planet c',
                position: {x: 1.3, y: 0, z: 0},
                velocity: {x: 0, y: 1.5, z: 0},
                mass: 0.1,
                color: '#27ae60',
                trailColor: '#27ae60',
                radius: 0.05,
            },
        ],
    },
    {
        id: '3d-helix',
        name: '3D Helix',
        description: '3D helical dance',
        category: 'fun',
        gravitationalConstant: 1,
        recommendedSpeed: 0.8,
        bodies: [
            {
                name: 'Body A',
                position: {x: 1, y: 0, z: 0.5},
                velocity: {x: 0, y: 0.5, z: 0.1},
                mass: 1,
                color: '#ff6b6b',
                trailColor: '#ff6b6b',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: -0.5, y: 0.866025, z: -0.25},
                velocity: {x: -0.433, y: -0.25, z: 0.1},
                mass: 1,
                color: '#4ecdc4',
                trailColor: '#4ecdc4',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: -0.5, y: -0.866025, z: -0.25},
                velocity: {x: 0.433, y: -0.25, z: -0.2},
                mass: 1,
                color: '#ffe66d',
                trailColor: '#ffe66d',
                radius: 0.08,
            },
        ],
    },
    {
        id: '3d-sphere',
        name: '3D Sphere Dance',
        description: 'Bodies orbiting in 3D',
        category: 'fun',
        gravitationalConstant: 1,
        recommendedSpeed: 0.6,
        bodies: [
            {
                name: 'Body A',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0, y: 0.3, z: 0.4},
                mass: 1,
                color: '#9b59b6',
                trailColor: '#9b59b6',
                radius: 0.08,
            },
            {
                name: 'Body B',
                position: {x: 0, y: 1, z: 0},
                velocity: {x: 0.4, y: 0, z: 0.3},
                mass: 1,
                color: '#1abc9c',
                trailColor: '#1abc9c',
                radius: 0.08,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 1},
                velocity: {x: 0.3, y: 0.4, z: 0},
                mass: 1,
                color: '#e74c3c',
                trailColor: '#e74c3c',
                radius: 0.08,
            },
        ],
    },
    {
        id: 'satellite-swap',
        name: 'Satellite Swap',
        description: 'Two stars exchanging a planet',
        category: 'fun',
        gravitationalConstant: 1,
        recommendedSpeed: 0.6,
        bodies: [
            {
                name: 'Star A',
                position: {x: -3, y: 0, z: 0},
                velocity: {x: 0.3, y: 0, z: 0},
                mass: 2,
                color: '#f39c12',
                trailColor: '#f39c12',
                radius: 0.12,
            },
            {
                name: 'Star B',
                position: {x: 3, y: 0, z: 0},
                velocity: {x: -0.3, y: 0, z: 0},
                mass: 2,
                color: '#e74c3c',
                trailColor: '#e74c3c',
                radius: 0.12,
            },
            {
                name: 'Planet',
                position: {x: -2, y: 0, z: 0},
                velocity: {x: 0.3, y: 1, z: 0},
                mass: 0.1,
                color: '#3498db',
                trailColor: '#3498db',
                radius: 0.05,
            },
        ],
    },

    // =====================================================
    // ARTISTIC
    // =====================================================
    {
        id: 'flower',
        name: 'Flower Pattern',
        description: 'Beautiful flower-like trails',
        category: 'artistic',
        gravitationalConstant: 1,
        recommendedSpeed: 1.2,
        bodies: [
            {
                name: 'Petal A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.34, y: 0.53, z: 0},
                mass: 1,
                color: '#ff69b4',
                trailColor: '#ff69b4',
                radius: 0.06,
            },
            {
                name: 'Petal B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.34, y: 0.53, z: 0},
                mass: 1,
                color: '#ff1493',
                trailColor: '#ff1493',
                radius: 0.06,
            },
            {
                name: 'Center',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.68, y: -1.06, z: 0},
                mass: 1,
                color: '#ffd700',
                trailColor: '#ffd700',
                radius: 0.06,
            },
        ],
    },
    {
        id: 'galaxy-spiral',
        name: 'Galaxy Spiral',
        description: 'Spiral galaxy-like patterns',
        category: 'artistic',
        gravitationalConstant: 0.8,
        recommendedSpeed: 0.8,
        bodies: [
            {
                name: 'Core',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: 0, y: 0, z: 0},
                mass: 3,
                color: '#ffeaa7',
                trailColor: '#ffeaa7',
                radius: 0.15,
            },
            {
                name: 'Arm A',
                position: {x: 1.5, y: 0.5, z: 0},
                velocity: {x: -0.2, y: 0.8, z: 0.1},
                mass: 0.5,
                color: '#74b9ff',
                trailColor: '#74b9ff',
                radius: 0.06,
            },
            {
                name: 'Arm B',
                position: {x: -1, y: -1.2, z: 0.2},
                velocity: {x: 0.6, y: -0.3, z: -0.1},
                mass: 0.5,
                color: '#a29bfe',
                trailColor: '#a29bfe',
                radius: 0.06,
            },
        ],
    },
    {
        id: 'infinity',
        name: 'Infinity Symbol',
        description: 'Traces an infinity pattern',
        category: 'artistic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Body A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.347, y: 0.533, z: 0},
                mass: 1,
                color: '#00cec9',
                trailColor: '#00cec9',
                radius: 0.07,
            },
            {
                name: 'Body B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.347, y: 0.533, z: 0},
                mass: 1,
                color: '#fd79a8',
                trailColor: '#fd79a8',
                radius: 0.07,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.694, y: -1.066, z: 0},
                mass: 1,
                color: '#fdcb6e',
                trailColor: '#fdcb6e',
                radius: 0.07,
            },
        ],
    },
    {
        id: 'neon-dance',
        name: 'Neon Dance',
        description: 'Vibrant neon patterns',
        category: 'artistic',
        gravitationalConstant: 1,
        recommendedSpeed: 0.7,
        bodies: [
            {
                name: 'Neon Pink',
                position: {x: 0.8, y: 0.6, z: 0},
                velocity: {x: -0.3, y: 0.4, z: 0},
                mass: 1,
                color: '#ff00ff',
                trailColor: '#ff00ff',
                radius: 0.08,
            },
            {
                name: 'Neon Cyan',
                position: {x: -0.8, y: 0.6, z: 0},
                velocity: {x: 0.3, y: 0.4, z: 0},
                mass: 1,
                color: '#00ffff',
                trailColor: '#00ffff',
                radius: 0.08,
            },
            {
                name: 'Neon Yellow',
                position: {x: 0, y: -1, z: 0},
                velocity: {x: 0, y: -0.3, z: 0},
                mass: 1.2,
                color: '#ffff00',
                trailColor: '#ffff00',
                radius: 0.09,
            },
        ],
    },
    {
        id: 'spirograph',
        name: 'Spirograph',
        description: 'Complex spirograph patterns',
        category: 'artistic',
        gravitationalConstant: 1,
        recommendedSpeed: 1.1,
        bodies: [
            {
                name: 'Body A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.2817, y: 0.4643, z: 0},
                mass: 1,
                color: '#e91e63',
                trailColor: '#e91e63',
                radius: 0.06,
            },
            {
                name: 'Body B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.2817, y: 0.4643, z: 0},
                mass: 1,
                color: '#2196f3',
                trailColor: '#2196f3',
                radius: 0.06,
            },
            {
                name: 'Body C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.5634, y: -0.9286, z: 0},
                mass: 1,
                color: '#4caf50',
                trailColor: '#4caf50',
                radius: 0.06,
            },
        ],
    },
    {
        id: 'celtic-knot',
        name: 'Celtic Knot',
        description: 'Intricate knotwork pattern',
        category: 'artistic',
        gravitationalConstant: 1,
        recommendedSpeed: 1,
        bodies: [
            {
                name: 'Strand A',
                position: {x: -1, y: 0, z: 0},
                velocity: {x: 0.25024, y: 0.43192, z: 0},
                mass: 1,
                color: '#c0392b',
                trailColor: '#c0392b',
                radius: 0.06,
            },
            {
                name: 'Strand B',
                position: {x: 1, y: 0, z: 0},
                velocity: {x: 0.25024, y: 0.43192, z: 0},
                mass: 1,
                color: '#27ae60',
                trailColor: '#27ae60',
                radius: 0.06,
            },
            {
                name: 'Strand C',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.50048, y: -0.86384, z: 0},
                mass: 1,
                color: '#f39c12',
                trailColor: '#f39c12',
                radius: 0.06,
            },
        ],
    },
    {
        id: 'aurora',
        name: 'Aurora',
        description: 'Northern lights-like waves',
        category: 'artistic',
        gravitationalConstant: 0.8,
        recommendedSpeed: 0.9,
        bodies: [
            {
                name: 'Green Wave',
                position: {x: -1.2, y: 0.3, z: 0},
                velocity: {x: 0.35, y: 0.45, z: 0},
                mass: 1,
                color: '#00ff7f',
                trailColor: '#00ff7f',
                radius: 0.07,
            },
            {
                name: 'Blue Wave',
                position: {x: 1.2, y: -0.3, z: 0},
                velocity: {x: 0.35, y: 0.45, z: 0},
                mass: 1,
                color: '#00bfff',
                trailColor: '#00bfff',
                radius: 0.07,
            },
            {
                name: 'Purple Wave',
                position: {x: 0, y: 0, z: 0},
                velocity: {x: -0.70, y: -0.90, z: 0},
                mass: 1,
                color: '#9370db',
                trailColor: '#9370db',
                radius: 0.07,
            },
        ],
    },
    {
        id: 'fireworks',
        name: 'Fireworks',
        description: 'Explosive radial patterns',
        category: 'artistic',
        gravitationalConstant: 0.6,
        recommendedSpeed: 0.8,
        bodies: [
            {
                name: 'Red Burst',
                position: {x: 0, y: 1.5, z: 0},
                velocity: {x: 0.5, y: -0.3, z: 0},
                mass: 0.8,
                color: '#ff0000',
                trailColor: '#ff0000',
                radius: 0.07,
            },
            {
                name: 'Gold Burst',
                position: {x: -1.3, y: -0.75, z: 0},
                velocity: {x: 0.1, y: 0.6, z: 0},
                mass: 0.8,
                color: '#ffd700',
                trailColor: '#ffd700',
                radius: 0.07,
            },
            {
                name: 'Silver Burst',
                position: {x: 1.3, y: -0.75, z: 0},
                velocity: {x: -0.6, y: -0.3, z: 0},
                mass: 0.8,
                color: '#c0c0c0',
                trailColor: '#c0c0c0',
                radius: 0.07,
            },
        ],
    },
    {
        id: 'dna-helix',
        name: 'DNA Helix',
        description: '3D double helix pattern',
        category: 'artistic',
        gravitationalConstant: 1,
        recommendedSpeed: 0.7,
        bodies: [
            {
                name: 'Strand A',
                position: {x: 1, y: 0, z: 0.3},
                velocity: {x: 0, y: 0.45, z: 0.15},
                mass: 1,
                color: '#e74c3c',
                trailColor: '#e74c3c',
                radius: 0.07,
            },
            {
                name: 'Strand B',
                position: {x: -0.5, y: 0.866, z: -0.15},
                velocity: {x: -0.39, y: -0.225, z: 0.15},
                mass: 1,
                color: '#3498db',
                trailColor: '#3498db',
                radius: 0.07,
            },
            {
                name: 'Core',
                position: {x: -0.5, y: -0.866, z: -0.15},
                velocity: {x: 0.39, y: -0.225, z: -0.30},
                mass: 1,
                color: '#2ecc71',
                trailColor: '#2ecc71',
                radius: 0.07,
            },
        ],
    },
];

export const getPresetsByCategory = (category: Preset['category']) => {
    return presets.filter((p) => p.category === category);
};

export const getPresetById = (id: string) => {
    return presets.find((p) => p.id === id);
};

export const getAllCategories = (): Preset['category'][] => {
    return ['famous', 'stable', 'periodic', 'chaotic', 'fun', 'artistic'];
};